/**
 * Simple ID generator for the Phase 1 mock store.
 * Phase 2: primary keys are UUIDs generated by the database server.
 */
export function generateId(prefix = 'id') {
  return `${prefix}-${Date.now()}-${Math.floor(Math.random() * 10000)}`
}
